import puppeteer from 'puppeteer';
const browser = await puppeteer.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', args: ['--no-sandbox'] });
const page = await browser.newPage();
await page.setViewport({ width: 1440, height: 900, deviceScaleFactor: 2 });
await page.goto('http://localhost:3000', { waitUntil: 'networkidle0' });
await new Promise(r => setTimeout(r, 800));
const nav = await page.$('.nav');
await nav.screenshot({ path: 'temporary screenshots/nav-logo.png' });
await browser.close();
console.log('done');
